// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1AEQT9VgCVLZAWo626Fp3tpU0TOmbik',
    appId: '1:541825298239:web:1ecebe8ac503628191ad8a',
    messagingSenderId: '541825298239',
    projectId: 'servicehub-92cea',
    authDomain: 'servicehub-92cea.firebaseapp.com',
    storageBucket: 'servicehub-92cea.firebasestorage.app',
    measurementId: 'G-R9MZD7Y2QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0w29Rda4l5yLFpRX8QL6tydF4qsME510',
    appId: '1:541825298239:android:c6a0c4ccd099be5f91ad8a',
    messagingSenderId: '541825298239',
    projectId: 'servicehub-92cea',
    storageBucket: 'servicehub-92cea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIl5nrwnIh8Op4oItHMxZb-kVeD36M3sE',
    appId: '1:541825298239:ios:e7f09174d787f82291ad8a',
    messagingSenderId: '541825298239',
    projectId: 'servicehub-92cea',
    storageBucket: 'servicehub-92cea.firebasestorage.app',
    androidClientId: '541825298239-rtb8s4lgo629l16t2i27ajfvq2uja6do.apps.googleusercontent.com',
    iosClientId: '541825298239-q5r9i36fd76l369jtscpt37u7h9eq2if.apps.googleusercontent.com',
    iosBundleId: 'com.example.servicehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIl5nrwnIh8Op4oItHMxZb-kVeD36M3sE',
    appId: '1:541825298239:ios:e7f09174d787f82291ad8a',
    messagingSenderId: '541825298239',
    projectId: 'servicehub-92cea',
    storageBucket: 'servicehub-92cea.firebasestorage.app',
    androidClientId: '541825298239-rtb8s4lgo629l16t2i27ajfvq2uja6do.apps.googleusercontent.com',
    iosClientId: '541825298239-q5r9i36fd76l369jtscpt37u7h9eq2if.apps.googleusercontent.com',
    iosBundleId: 'com.example.servicehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk1AEQT9VgCVLZAWo626Fp3tpU0TOmbik',
    appId: '1:541825298239:web:b5eecb890d0b284c91ad8a',
    messagingSenderId: '541825298239',
    projectId: 'servicehub-92cea',
    authDomain: 'servicehub-92cea.firebaseapp.com',
    storageBucket: 'servicehub-92cea.firebasestorage.app',
    measurementId: 'G-QC2DH6GJKR',
  );
}
